name: AligatorMobile
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^1.2.1+3
  flutter_mobx: ^1.1.0+2

  mock_data: ^1.2.8
  dartz: ^0.9.2
  equatable: ^1.2.5

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.3
  mobx_codegen: ^1.1.1+1

  mockito: ^4.1.3

flutter:
  uses-material-design: true

scripts:
    build_runner: flutter pub run build_runner build --delete-conflicting-outputs
